version: "2"

linters:
  enable:
    - errcheck
    - errname
    - exhaustive
    - godot
    - govet
    - ineffassign
    - lll
    - staticcheck
    - testpackage
    - unused
    - usestdlibvars
    - whitespace
  exclusions:
    rules:
      - linters:
          - lll
        source: '^\s*\w+\s+[^`]+`[^`]+`$'
      - linters:
          - typecheck
        text: "could not import gopkg.in/gographics/imagick.v3/imagick"

formatters:
  enable:
    - goimports
  settings:
    goimports:
      local-prefixes:
        - github.com/fogo-sh/borik
