services:
  borik:
    image: ghcr.io/fogo-sh/borik
    restart: always
    build: .
    env_file:
      - .env
    environment:
      - BORIK_NODE_RENDERER_URL=http://renderer:3001
    depends_on:
      - renderer
  renderer:
    build: ./node-renderer
    restart: always
