package activities

import "go.temporal.io/sdk/worker"

func RegisterActivities(worker worker.Worker) {
	worker.RegisterActivity(LoadImage)
	worker.RegisterActivity(SplitImage)
	worker.RegisterActivity(JoinImage)

	worker.RegisterActivity(Magik)
	worker.RegisterActivity(Lagik)
	worker.RegisterActivity(Gmagik)
	worker.RegisterActivity(Arcweld)
	worker.RegisterActivity(Malt)
	worker.RegisterActivity(Deepfry)
	worker.RegisterActivity(Divine)
	worker.RegisterActivity(PresidentsFrame)
	worker.RegisterActivity(Heritage)
	worker.RegisterActivity(Shinji)
	worker.RegisterActivity(Waaw)
	worker.RegisterActivity(Haah)
	worker.RegisterActivity(Woow)
	worker.RegisterActivity(Hooh)
	worker.RegisterActivity(Invert)
	worker.RegisterActivity(Otsu)
	worker.RegisterActivity(Rotate)
	worker.RegisterActivity(Resize)
	worker.RegisterActivity(HueCycle)
	worker.RegisterActivity(Modulate)
	worker.RegisterActivity(Meme)
	worker.RegisterActivity(Hdr)
	worker.RegisterActivity(EGA)
	worker.RegisterActivity(TempleOS)
	worker.RegisterActivity(CGA)
	worker.RegisterActivity(JackPog)
	worker.RegisterActivity(SideKeenan)
	worker.RegisterActivity(KeenanThumb)
	worker.RegisterActivity(MitchPoint)
	worker.RegisterActivity(StevePoint)
	worker.RegisterActivity(AndrewPog)
	worker.RegisterActivity(MatlabKid)
	worker.RegisterActivity(NatalieClimb)
	worker.RegisterActivity(DennyStanding)
	worker.RegisterActivity(GenerateImage)
	worker.RegisterActivity(ImageEdit)
	worker.RegisterActivity(LoopEdit)
	worker.RegisterActivity(FlipFlop)
	worker.RegisterActivity(AiZoom)
	worker.RegisterActivity(AiLoopZoom)
}
