name: Validate

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read
  pull-requests: read
  checks: write

jobs:
  golangci-lint:
    uses: nint8835/workflows/.github/workflows/golangci-lint.yaml@main
